let handler = async (m, { conn }) => {
	let img = "https://i.ibb.co/305yt26/bf84f20635dedd5dde31e7e5b6983ae9.jpg";
	let dares = [
		"Foto kuburan tengah malam berani ga?",
		"Ambil foto bot, jadikan foto profil kamu selama 1 hari",
		"VN nyanyi balonku ada 5",
		"Minum Coca-Cola sampai habis tanpa sendawa selama 30 detik",
		"Makan 1 Cabe tanpa minum, tanpa gorengan selama 2 menit",
		"Celupin hp kamu ke air selama 30 detik",
		"VN *Aku sayang kamu*",
		"Nyanyi potong bebek angsa (VN)",
		"Kirim pesan ke mantan kamu dan bilang _aku masih suka sama kamu_",
		"Telfon crush/pacar sekarang dan ss ke pemain",
		"Pap ke salah satu anggota grup",
		"Pap apa yang di depan kamu",
		"SS recent call whatsapp",
		"Kirim voice note bilang can i call u baby?",
		"Pake foto sule sampe 3 hari",
		"Ketik pake bahasa daerah 24 jam",
		"Ganti nama menjadi _gue anak lucinta luna_ selama 5 jam",
		"Chat ke kontak wa urutan sesuai %batre kamu, terus bilang ke dia _i lucky to hv you_",
		"Prank chat mantan dan bilang *i love u, pgn balikan*",
		"Record voice baca surah al-kautsar",
		"Ganti nama jadi *BOWO* selama 24 jam",
		"Sebutkan tipe pacar mu!",
		"VN *aku mencintaimu*",
		"Kamu harus pap sekarang!",
		"Kamu harus bagi bagi limit, minimal 2 setiap pengguna",
		"Chatingan selama 1 jam harus 4l4Y 8AN93T",
		"Selfie sambil ngedance dan kirim ke grup",
		"Kirim voice note menirukan suara hewan",
		"Buat video lucu dan kirim ke teman-teman",
		"Ganti status wa dengan kata-kata aneh selama 24 jam",
		"Tulis 'Aku suka seseorang di grup ini' tanpa sebut nama",
		"Ubah nama di wa menjadi 'Si Misterius' selama sehari",
		"Buat meme dari foto diri sendiri dan bagikan di grup",
		"Kirim voice note mengucapkan selamat pagi dengan suara manja",
		"Lakukan push-up 10 kali dan kirim videonya",
		"Pakai aksen asing dan bicaralah selama 5 menit",
		"Makan sesuatu yang aneh di rumahmu dan deskripsikan rasanya",
		"Nyanyikan lagu favoritmu dengan gaya opera (VN)",
		"Berikan pujian berlebihan kepada seseorang di grup",
		"Kirim pesan cinta kepada seseorang yang kamu suka di grup",
		"Posting foto lama dan ceritakan kisah di baliknya",
		"VN bilang 'Aku adalah robot yang menguasai dunia'",
		"Kirim video menirukan tarian viral TikTok",
		"Buat story dengan filter yang paling lucu dan simpan selama 24 jam",
		"Kirim voice note bilang 'Aku suka keju' dengan nada dramatis",
		"Ceritakan lelucon terburuk yang kamu tahu",
		"Tulis status wa dengan teks acak dan biarkan selama sehari",
		"Ganti nama kontak terdekatmu menjadi 'Sahabat Sejati' selama 24 jam",
		"Buat selfie dengan ekspresi teraneh dan kirim ke grup",
		"VN nyanyi lagu anak-anak dengan suara seriosa",
		"Ceritakan mimpi teraneh yang pernah kamu alami",
		"Lakukan impersonasi dari karakter kartun favoritmu (VN)",
		"Posting foto makanan favoritmu dan beri caption lucu",
		"Berikan saran kocak tentang 'Cara menjadi alien yang baik'",
		"Kirim video memperagakan olahraga favoritmu secara lucu",
		"Tulis puisi singkat tentang 'Cinta pada pandangan pertama'",
		"Buat video 'gugup' saat mengaku perasaan palsu pada seseorang",
		"Kirim voice note membaca puisi dengan penuh perasaan",
		"Ubah nama di wa menjadi 'Raja Tawa' selama sehari",
		"Kirim voice note menirukan suara binatang peliharaan",
		"Deskripsikan hari terburukmu dengan gaya komedi",
		"Nyanyikan lagu 'Happy Birthday' dengan nada yang salah (VN)",
	];
	let der = dares[Math.floor(Math.random() * dares.length)];
	conn.sendFile(m.chat, img, "dare.png", `*DARE*\n\n“${der}”`, m);
};
handler.help = ["dare"];
handler.tags = ["fun"];
handler.command = /^(dare|berani|tantangan)$/i;
handler.limit = true;

export default handler;
